// Auto-generated theme: default-light
export const sc2020Theme = {
  "themeName": "sc2020",
  "iconSet": "v1",
  "isLight": true,
  "cssVariables": {
    "--sjs2-base-unit-size": "8px",
    "--sjs2-base-unit-spacing": "8px",
    "--sjs2-base-unit-radius": "8px",
    "--sjs2-base-unit-border-width": "1px",
    "--sjs2-base-unit-font-size": "8px",
    "--sjs2-base-unit-line-height": "8px",
    "--sjs2-base-unit-opacity": "1%",
    "--sjs2-base-unit-scale": "1%",
    "--sjs2-scale-x000": "calc(var(--sjs2-base-unit-scale) * 0)",
    "--sjs2-scale-x025": "calc(var(--sjs2-base-unit-scale) * 25)",
    "--sjs2-scale-x050": "calc(var(--sjs2-base-unit-scale) * 50)",
    "--sjs2-scale-x075": "calc(var(--sjs2-base-unit-scale) * 75)",
    "--sjs2-scale-x095": "calc(var(--sjs2-base-unit-scale) * 95)",
    "--sjs2-scale-x100": "calc(var(--sjs2-base-unit-scale) * 100)",
    "--sjs2-scale-x200": "calc(var(--sjs2-base-unit-scale) * 200)",
    "--sjs2-size-x000": "calc(var(--sjs2-base-unit-size) * 0)",
    "--sjs2-size-x025": "calc(var(--sjs2-base-unit-size) * 0.25)",
    "--sjs2-size-x050": "calc(var(--sjs2-base-unit-size) * 0.50)",
    "--sjs2-size-x075": "calc(var(--sjs2-base-unit-size) * 0.75)",
    "--sjs2-size-x100": "calc(var(--sjs2-base-unit-size) * 1)",
    "--sjs2-size-x150": "calc(var(--sjs2-base-unit-size) * 1.50)",
    "--sjs2-size-x200": "calc(var(--sjs2-base-unit-size) * 2)",
    "--sjs2-size-x250": "calc(var(--sjs2-base-unit-size) * 2.50)",
    "--sjs2-size-x300": "calc(var(--sjs2-base-unit-size) * 3)",
    "--sjs2-size-x350": "calc(var(--sjs2-base-unit-size) * 3.50)",
    "--sjs2-size-x400": "calc(var(--sjs2-base-unit-size) * 4)",
    "--sjs2-size-x500": "calc(var(--sjs2-base-unit-size) * 5)",
    "--sjs2-size-x600": "calc(var(--sjs2-base-unit-size) * 6)",
    "--sjs2-size-x700": "calc(var(--sjs2-base-unit-size) * 7)",
    "--sjs2-size-x800": "calc(var(--sjs2-base-unit-size) * 8)",
    "--sjs2-size-x900": "calc(var(--sjs2-base-unit-size) * 9)",
    "--sjs2-size-x1000": "calc(var(--sjs2-base-unit-size) * 10)",
    "--sjs2-size-x1100": "calc(var(--sjs2-base-unit-size) * 11)",
    "--sjs2-size-x1200": "calc(var(--sjs2-base-unit-size) * 12)",
    "--sjs2-size-x1300": "calc(var(--sjs2-base-unit-size) * 13)",
    "--sjs2-size-x1400": "calc(var(--sjs2-base-unit-size) * 14)",
    "--sjs2-size-x1500": "calc(var(--sjs2-base-unit-size) * 15)",
    "--sjs2-radius-x000": "calc(var(--sjs2-base-unit-radius) * 0)",
    "--sjs2-radius-x025": "calc(var(--sjs2-base-unit-radius) * 0.25)",
    "--sjs2-radius-x050": "calc(var(--sjs2-base-unit-radius) * 0.50)",
    "--sjs2-radius-x075": "calc(var(--sjs2-base-unit-radius) * 0.75)",
    "--sjs2-radius-x100": "calc(var(--sjs2-base-unit-radius) * 1)",
    "--sjs2-radius-x150": "calc(var(--sjs2-base-unit-radius) * 1.50)",
    "--sjs2-radius-x200": "calc(var(--sjs2-base-unit-radius) * 2)",
    "--sjs2-radius-x250": "calc(var(--sjs2-base-unit-radius) * 2.50)",
    "--sjs2-radius-x300": "calc(var(--sjs2-base-unit-radius) * 3)",
    "--sjs2-radius-x400": "calc(var(--sjs2-base-unit-radius) * 4)",
    "--sjs2-radius-x500": "calc(var(--sjs2-base-unit-radius) * 5)",
    "--sjs2-radius-x600": "calc(var(--sjs2-base-unit-radius) * 6)",
    "--sjs2-radius-x700": "calc(var(--sjs2-base-unit-radius) * 7)",
    "--sjs2-radius-x800": "calc(var(--sjs2-base-unit-radius) * 8)",
    "--sjs2-radius-round": "9999px",
    "--sjs2-spacing-x000": "calc(var(--sjs2-base-unit-spacing) * 0)",
    "--sjs2-spacing-x025": "calc(var(--sjs2-base-unit-spacing) * 0.25)",
    "--sjs2-spacing-x050": "calc(var(--sjs2-base-unit-spacing) * 0.50)",
    "--sjs2-spacing-x075": "calc(var(--sjs2-base-unit-spacing) * 0.75)",
    "--sjs2-spacing-x100": "calc(var(--sjs2-base-unit-spacing) * 1)",
    "--sjs2-spacing-x150": "calc(var(--sjs2-base-unit-spacing) * 1.5)",
    "--sjs2-spacing-x200": "calc(var(--sjs2-base-unit-spacing) * 2)",
    "--sjs2-spacing-x250": "calc(var(--sjs2-base-unit-spacing) * 2.50)",
    "--sjs2-spacing-x300": "calc(var(--sjs2-base-unit-spacing) * 3)",
    "--sjs2-spacing-x400": "calc(var(--sjs2-base-unit-spacing) * 4)",
    "--sjs2-spacing-x500": "calc(var(--sjs2-base-unit-spacing) * 5)",
    "--sjs2-spacing-x600": "calc(var(--sjs2-base-unit-spacing) * 6)",
    "--sjs2-spacing-x700": "calc(var(--sjs2-base-unit-spacing) * 7)",
    "--sjs2-spacing-x800": "calc(var(--sjs2-base-unit-spacing) * 8)",
    "--sjs2-spacing-negative-x025": "calc(var(--sjs2-base-unit-spacing) * -0.25)",
    "--sjs2-spacing-negative-x050": "calc(var(--sjs2-base-unit-spacing) * -0.50)",
    "--sjs2-spacing-negative-x075": "calc(var(--sjs2-base-unit-spacing) * -0.75)",
    "--sjs2-spacing-negative-x100": "calc(var(--sjs2-base-unit-spacing) * -1)",
    "--sjs2-spacing-negative-x150": "calc(var(--sjs2-base-unit-spacing) * -1.5)",
    "--sjs2-spacing-negative-x200": "calc(var(--sjs2-base-unit-spacing) * -2)",
    "--sjs2-spacing-negative-x250": "calc(var(--sjs2-base-unit-spacing) * -2.50)",
    "--sjs2-spacing-negative-x300": "calc(var(--sjs2-base-unit-spacing) * -3)",
    "--sjs2-spacing-negative-x400": "calc(var(--sjs2-base-unit-spacing) * -4)",
    "--sjs2-spacing-negative-x500": "calc(var(--sjs2-base-unit-spacing) * -5)",
    "--sjs2-spacing-negative-x600": "calc(var(--sjs2-base-unit-spacing) * -6)",
    "--sjs2-spacing-negative-x700": "calc(var(--sjs2-base-unit-spacing) * -7)",
    "--sjs2-spacing-negative-x800": "calc(var(--sjs2-base-unit-spacing) * -8)",
    "--sjs2-opacity-x000": "calc(var(--sjs2-base-unit-opacity) * 0)",
    "--sjs2-opacity-x005": "calc(var(--sjs2-base-unit-opacity) * 5)",
    "--sjs2-opacity-x010": "calc(var(--sjs2-base-unit-opacity) * 10)",
    "--sjs2-opacity-x015": "calc(var(--sjs2-base-unit-opacity) * 15)",
    "--sjs2-opacity-x020": "calc(var(--sjs2-base-unit-opacity) * 20)",
    "--sjs2-opacity-x025": "calc(var(--sjs2-base-unit-opacity) * 25)",
    "--sjs2-opacity-x030": "calc(var(--sjs2-base-unit-opacity) * 30)",
    "--sjs2-opacity-x035": "calc(var(--sjs2-base-unit-opacity) * 35)",
    "--sjs2-opacity-x040": "calc(var(--sjs2-base-unit-opacity) * 40)",
    "--sjs2-opacity-x045": "calc(var(--sjs2-base-unit-opacity) * 45)",
    "--sjs2-opacity-x050": "calc(var(--sjs2-base-unit-opacity) * 50)",
    "--sjs2-opacity-x055": "calc(var(--sjs2-base-unit-opacity) * 55)",
    "--sjs2-opacity-x060": "calc(var(--sjs2-base-unit-opacity) * 60)",
    "--sjs2-opacity-x065": "calc(var(--sjs2-base-unit-opacity) * 65)",
    "--sjs2-opacity-x070": "calc(var(--sjs2-base-unit-opacity) * 70)",
    "--sjs2-opacity-x075": "calc(var(--sjs2-base-unit-opacity) * 75)",
    "--sjs2-opacity-x080": "calc(var(--sjs2-base-unit-opacity) * 80)",
    "--sjs2-opacity-x085": "calc(var(--sjs2-base-unit-opacity) * 85)",
    "--sjs2-opacity-x090": "calc(var(--sjs2-base-unit-opacity) * 90)",
    "--sjs2-opacity-x095": "calc(var(--sjs2-base-unit-opacity) * 95)",
    "--sjs2-opacity-x100": "calc(var(--sjs2-base-unit-opacity) * 100)",
    "--sjs2-border-width-x000": "calc(var(--sjs2-base-unit-border-width) * 0)",
    "--sjs2-border-width-x100": "calc(var(--sjs2-base-unit-border-width) * 1)",
    "--sjs2-border-width-x200": "calc(var(--sjs2-base-unit-border-width) * 2)",
    "--sjs2-border-width-x400": "calc(var(--sjs2-base-unit-border-width) * 4)",
    "--sjs2-font-weight-regular": "Regular",
    "--sjs2-font-weight-medium": "Medium",
    "--sjs2-font-weight-semibold": "SemiBold",
    "--sjs2-font-weight-bold": "Bold",
    "--sjs2-font-size-x000": "calc(var(--sjs2-base-unit-font-size) * 0)",
    "--sjs2-font-size-x100": "calc(var(--sjs2-base-unit-font-size) * 1)",
    "--sjs2-font-size-x150": "calc(var(--sjs2-base-unit-font-size) * 1.5)",
    "--sjs2-font-size-x200": "calc(var(--sjs2-base-unit-font-size) * 2)",
    "--sjs2-font-size-x250": "calc(var(--sjs2-base-unit-font-size) * 2.5)",
    "--sjs2-font-size-x300": "calc(var(--sjs2-base-unit-font-size) * 3)",
    "--sjs2-font-size-x350": "calc(var(--sjs2-base-unit-font-size) * 3.5)",
    "--sjs2-font-size-x400": "calc(var(--sjs2-base-unit-font-size) * 4)",
    "--sjs2-font-size-x500": "calc(var(--sjs2-base-unit-font-size) * 5)",
    "--sjs2-font-size-x600": "calc(var(--sjs2-base-unit-font-size) * 6)",
    "--sjs2-line-height-x000": "calc(var(--sjs2-base-unit-line-height) * 0)",
    "--sjs2-line-height-x100": "calc(var(--sjs2-base-unit-line-height) * 1)",
    "--sjs2-line-height-x200": "calc(var(--sjs2-base-unit-line-height) * 2)",
    "--sjs2-line-height-x300": "calc(var(--sjs2-base-unit-line-height) * 3)",
    "--sjs2-line-height-x400": "calc(var(--sjs2-base-unit-line-height) * 4)",
    "--sjs2-line-height-x500": "calc(var(--sjs2-base-unit-line-height) * 5)",
    "--sjs2-line-height-x600": "calc(var(--sjs2-base-unit-line-height) * 6)",
    "--sjs2-text-case-default": "none",
    "--sjs2-text-case-uppercase": "uppercase",
    "--sjs2-palette-gray-100": "#F5F5F5",
    "--sjs2-palette-gray-150": "#EDEDED",
    "--sjs2-palette-gray-200": "#E5E5E5",
    "--sjs2-palette-gray-250": "#D4D4D4",
    "--sjs2-palette-gray-300": "#CDCDCD",
    "--sjs2-palette-gray-400": "#B3B2B2",
    "--sjs2-palette-gray-500": "#8E8E8E",
    "--sjs2-palette-gray-600": "#5F5E61",
    "--sjs2-palette-gray-700": "#424146",
    "--sjs2-palette-gray-750": "#36353C",
    "--sjs2-palette-gray-800": "#2D2C33",
    "--sjs2-palette-gray-900": "#1C1B20",
    "--sjs2-palette-gray-950": "#161519",
    "--sjs2-palette-gray-999": "#111014",
    "--sjs2-palette-gray-000": "#fff",
    "--sjs2-palette-red-400": "#ff6e84",
    "--sjs2-palette-red-600": "#E50A3E",
    "--sjs2-palette-red-700": "#C30935",
    "--sjs2-palette-green-400": "#15CDAB",
    "--sjs2-palette-green-600": "#19B394",
    "--sjs2-palette-green-700": "#15947A",
    "--sjs2-palette-blue-400": "#66B4FC",
    "--sjs2-palette-blue-600": "#437FD9",
    "--sjs2-palette-blue-700": "#2A6CD0",
    "--sjs2-palette-yellow-400": "#FEC64A",
    "--sjs2-palette-yellow-600": "#FF9814",
    "--sjs2-palette-yellow-700": "#F08700",
    "--sjs2-palette-violet-400": "#C36FF4",
    "--sjs2-palette-violet-600": "#A62CEC",
    "--sjs2-palette-violet-700": "#9614E1",
    "--sjs2-palette-olive-400": "#6FC648",
    "--sjs2-palette-olive-600": "#4FAF24",
    "--sjs2-palette-olive-700": "#41901E",
    "--sjs2-palette-purple-400": "#A190FA",
    "--sjs2-palette-purple-600": "#6E5BD1",
    "--sjs2-palette-purple-700": "#5640C9",
    "--sjs2-palette-indianred-400": "#F9786A",
    "--sjs2-palette-indianred-600": "#AF496B",
    "--sjs2-palette-indianred-700": "#973F5C",
    "--sjs2-radius-semantic-form": "var(--sjs2-radius-x100)",
    "--sjs2-radius-semantic-form-item": "var(--sjs2-radius-x050)",
    "--sjs2-radius-control-action": "var(--sjs2-radius-semantic-form)",
    "--sjs2-radius-control-action-icon": "var(--sjs2-radius-semantic-form)",
    "--sjs2-radius-control-button": "var(--sjs2-radius-semantic-form)",
    "--sjs2-radius-control-menu-item": "var(--sjs2-radius-semantic-form)",
    "--sjs2-radius-control-drop-item": "var(--sjs2-radius-x100)",
    "--sjs2-radius-control-checkbox": "var(--sjs2-radius-semantic-form-item)",
    "--sjs2-radius-control-rating": "var(--sjs2-radius-round)",
    "--sjs2-radius-control-ranking": "var(--sjs2-radius-round)",
    "--sjs2-radius-control-ranking-item": "var(--sjs2-radius-round)",
    "--sjs2-radius-control-toggle": "var(--sjs2-radius-round)",
    "--sjs2-radius-control-toggle-item": "var(--sjs2-radius-round)",
    "--sjs2-radius-control-track": "var(--sjs2-radius-round)",
    "--sjs2-radius-control-track-item": "var(--sjs2-radius-round)",
    "--sjs2-radius-control-track-thumb": "var(--sjs2-radius-round)",
    "--sjs2-radius-container-panel": "var(--sjs2-radius-x200)",
    "--sjs2-radius-container-panel-nested": "var(--sjs2-radius-x100)",
    "--sjs2-radius-container-menu": "var(--sjs2-radius-x250)",
    "--sjs2-radius-container-drop": "var(--sjs2-radius-x200)",
    "--sjs2-radius-container-modal": "var(--sjs2-radius-x300)",
    "--sjs2-radius-container-notifier": "var(--sjs2-radius-x200)",
    "--sjs2-radius-container-tooltip": "var(--sjs2-radius-x100)",
    "--sjs2-layout-control-formbox-small-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-formbox-small-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-formbox-small-gap": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-formbox-medium-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-formbox-medium-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-formbox-medium-gap": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-message-small-spacer": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-message-small-horizontal": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-message-small-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-message-small-gap": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-message-medium-spacer": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-message-medium-horizontal": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-message-medium-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-message-medium-gap": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-small-content-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-input-small-content-horizontal": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-small-swatch-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-input-small-swatch-left": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-small-swatch-right": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-input-small-icon-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-input-small-icon-left": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-input-small-icon-right": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-input-small-label-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-input-small-label-horizontal": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-small-group-gap": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-input-small-limit-vertical": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-input-small-limit-left": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-small-limit-right": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-medium-content-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-medium-content-horizontal": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-input-medium-swatch-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-medium-swatch-left": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-input-medium-swatch-right": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-input-medium-icon-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-medium-icon-left": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-medium-icon-right": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-input-medium-label-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-medium-label-horizontal": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-input-medium-group-gap": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-input-medium-limit-vertical": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-input-medium-limit-left": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-input-medium-limit-right": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-action-xx-small-label-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-xx-small-label-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-xx-small-icon-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-xx-small-icon-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-xx-small-box-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-xx-small-box-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-xx-small-box-gap": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-xx-small-addon-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-xx-small-addon-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-x-small-label-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-x-small-label-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-x-small-icon-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-x-small-icon-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-x-small-box-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-x-small-box-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-x-small-box-gap": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-x-small-addon-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-x-small-addon-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-small-label-horizontal": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-action-small-label-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-small-icon-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-small-icon-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-small-box-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-action-small-box-horizontal": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-action-small-box-gap": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-small-addon-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-small-addon-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-medium-label-horizontal": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-action-medium-label-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-medium-icon-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-medium-icon-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-medium-box-vertical": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-action-medium-box-horizontal": "var(--sjs2-spacing-x150)",
    "--sjs2-layout-control-action-medium-box-gap": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-medium-addon-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-medium-addon-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-large-label-horizontal": "var(--sjs2-spacing-x200)",
    "--sjs2-layout-control-action-large-label-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-large-icon-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-large-icon-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-large-box-vertical": "var(--sjs2-spacing-x200)",
    "--sjs2-layout-control-action-large-box-horizontal": "var(--sjs2-spacing-x200)",
    "--sjs2-layout-control-action-large-box-gap": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-action-large-addon-vertical": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-action-large-addon-horizontal": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-caption-small-box-left": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-small-box-right": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-caption-small-box-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-small-box-gap": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-caption-small-group-gap": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-small-description-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-small-description-top": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-small-description-bottom": "var(--sjs2-spacing-x200)",
    "--sjs2-layout-control-caption-small-caption-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-small-caption-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-control-caption-medium-box-left": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-medium-box-right": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-caption-medium-box-vertical": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-medium-box-gap": "var(--sjs2-spacing-x050)",
    "--sjs2-layout-control-caption-medium-group-gap": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-medium-description-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-medium-description-top": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-medium-description-bottom": "var(--sjs2-spacing-x200)",
    "--sjs2-layout-control-caption-medium-caption-horizontal": "var(--sjs2-spacing-x000)",
    "--sjs2-layout-control-caption-medium-caption-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-container-drop-horizontal": "var(--sjs2-spacing-x100)",
    "--sjs2-layout-container-drop-vertical": "var(--sjs2-spacing-x100)",
    "--sjs2-size-semantic-xx-small": "var(--sjs2-size-x300)",
    "--sjs2-size-semantic-x-small": "var(--sjs2-size-x400)",
    "--sjs2-size-semantic-small": "var(--sjs2-size-x500)",
    "--sjs2-size-semantic-medium": "var(--sjs2-size-x600)",
    "--sjs2-size-semantic-large": "var(--sjs2-size-x700)",
    "--sjs2-size-icon-small": "var(--sjs2-size-x200)",
    "--sjs2-size-icon-medium": "var(--sjs2-size-x300)",
    "--sjs2-size-icon-large": "var(--sjs2-size-x400)",
    "--sjs2-is-panelless": "false",
    "--sjs2-typography-font-family-default": "Open Sans",
    "--sjs2-typography-font-family-code": "DM Mono",
    "--sjs2-typography-font-size-small": "var(--sjs2-font-size-x150)",
    "--sjs2-typography-font-size-default": "var(--sjs2-font-size-x200)",
    "--sjs2-typography-font-size-medium": "var(--sjs2-font-size-x300)",
    "--sjs2-typography-font-size-large": "var(--sjs2-font-size-x400)",
    "--sjs2-typography-line-height-small": "var(--sjs2-line-height-x200)",
    "--sjs2-typography-line-height-default": "var(--sjs2-line-height-x300)",
    "--sjs2-typography-line-height-medium": "var(--sjs2-line-height-x400)",
    "--sjs2-typography-line-height-large": "var(--sjs2-line-height-x500)",
    "--sjs2-typography-font-weight-default": "var(--sjs2-font-weight-regular)",
    "--sjs2-typography-font-weight-strong": "var(--sjs2-font-weight-semibold)",
    "--sjs2-color-project-brand-400": "hsl(from #19B394 h s calc(l * 1.1))",
    "--sjs2-color-project-brand-600": "#19B394",
    "--sjs2-color-project-brand-700": "hsl(from #19B394 h s calc(l * 0.85))",
    "--sjs2-color-project-accent-400": "hsl(from #19B394 h s calc(l * 1.1))",
    "--sjs2-color-project-accent-600": "#19B394",
    "--sjs2-color-project-accent-700": "hsl(from #19B394 h s calc(l * 0.85))",
    "--sjs2-color-utility-body": "var(--sjs2-palette-gray-000)",
    "--sjs2-color-utility-surface": "#F3F3F3",
    "--sjs2-color-utility-surface-muted": "#F3F3F3",
    "--sjs2-color-utility-sheet": "#FFFFFF",
    "--sjs2-color-utility-scrollbar": "#00000026",
    "--sjs2-color-utility-a11y": "#326FCA99",
    "--sjs2-color-utility-overlay-screen": "#90909080",
    "--sjs2-color-utility-overlay-border": "rgba(from var(--sjs2-palette-gray-900) r g b / var(--sjs2-opacity-x040))",
    "--sjs2-color-utility-shadow-surface-default": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-hovered": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-pressed": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-focused": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-surface-disabled": "rgba(from var(--sjs2-palette-gray-999) r g b / var(--sjs2-opacity-x010))",
    "--sjs2-color-utility-shadow-elevated-default": "rgba(from #004C44 r g b / var(--sjs2-opacity-x015))",
    "--sjs2-color-utility-shadow-floating-default": "rgba(from #004C44 r g b / var(--sjs2-opacity-x020))",
    "--sjs2-color-bg-basic-primary": "#FFFFFF",
    "--sjs2-color-bg-basic-secondary": "#F3F3F3",
    "--sjs2-color-bg-basic-tertiary": "#E8E8E8",
    "--sjs2-color-bg-basic-primary-dim": "#F8F8F8",
    "--sjs2-color-bg-basic-secondary-dim": "#E8E8E8",
    "--sjs2-color-bg-basic-tertiary-dim": "#E0E0E0",
    "--sjs2-color-bg-brand-primary": "#19B394",
    "--sjs2-color-bg-brand-secondary": "#19B3941A",
    "--sjs2-color-bg-brand-tertiary": "#19B39400",
    "--sjs2-color-bg-brand-primary-dim": "#14A48B",
    "--sjs2-color-bg-brand-secondary-dim": "#19B39426",
    "--sjs2-color-bg-brand-tertiary-dim": "#19B3941A",
    "--sjs2-color-bg-accent-primary": "#FF9814",
    "--sjs2-color-bg-accent-secondary": "#FF98141A",
    "--sjs2-color-bg-accent-tertiary": "#FF981400",
    "--sjs2-color-bg-accent-primary-dim": "#E68A12",
    "--sjs2-color-bg-accent-secondary-dim": "#FF981426",
    "--sjs2-color-bg-accent-tertiary-dim": "#FF98141A",
    "--sjs2-color-bg-note-primary": "#437FD9",
    "--sjs2-color-bg-note-secondary": "#437FD91A",
    "--sjs2-color-bg-note-tertiary": "#437FD900",
    "--sjs2-color-bg-note-primary-dim": "#3A6FC4",
    "--sjs2-color-bg-note-secondary-dim": "#437FD926",
    "--sjs2-color-bg-note-tertiary-dim": "#437FD91A",
    "--sjs2-color-bg-neutral-primary": "#000000E8",
    "--sjs2-color-bg-neutral-secondary": "#0000001A",
    "--sjs2-color-bg-neutral-tertiary": "#00000000",
    "--sjs2-color-bg-neutral-primary-dim": "#000000BF",
    "--sjs2-color-bg-neutral-secondary-dim": "#0000001A",
    "--sjs2-color-bg-neutral-tertiary-dim": "#0000000D",
    "--sjs2-color-bg-positive-primary": "#19B394",
    "--sjs2-color-bg-positive-secondary": "#19B3941A",
    "--sjs2-color-bg-positive-tertiary": "#19B39400",
    "--sjs2-color-bg-positive-primary-dim": "#15947A",
    "--sjs2-color-bg-positive-secondary-dim": "#19B39426",
    "--sjs2-color-bg-positive-tertiary-dim": "#19B3941A",
    "--sjs2-color-bg-warning-primary": "#FF9814",
    "--sjs2-color-bg-warning-secondary": "#FF98141A",
    "--sjs2-color-bg-warning-tertiary": "#FF981400",
    "--sjs2-color-bg-warning-primary-dim": "#E68A12",
    "--sjs2-color-bg-warning-secondary-dim": "#FF981426",
    "--sjs2-color-bg-warning-tertiary-dim": "#FF98141A",
    "--sjs2-color-bg-alert-primary": "#E50A3E",
    "--sjs2-color-bg-alert-secondary": "#E50A3E1A",
    "--sjs2-color-bg-alert-tertiary": "#E50A3E00",
    "--sjs2-color-bg-alert-primary-dim": "#CC0938",
    "--sjs2-color-bg-alert-secondary-dim": "#E50A3E26",
    "--sjs2-color-bg-alert-tertiary-dim": "#E50A3E1A",
    "--sjs2-color-bg-static-main-primary": "#000000E8",
    "--sjs2-color-bg-static-main-secondary": "#0000001A",
    "--sjs2-color-bg-static-main-primary-dim": "#000000BF",
    "--sjs2-color-bg-static-main-secondary-dim": "#00000026",
    "--sjs2-color-bg-static-sub-primary": "#FFFFFF",
    "--sjs2-color-bg-static-sub-secondary": "#FFFFFF1A",
    "--sjs2-color-bg-static-sub-primary-dim": "#F5F5F5",
    "--sjs2-color-bg-static-sub-secondary-dim": "#FFFFFF26",
    "--sjs2-color-bg-state-common-disabled": "#CDCDCD",
    "--sjs2-color-fg-basic-primary": "#000000E8",
    "--sjs2-color-fg-basic-primary-muted": "#000000BF",
    "--sjs2-color-fg-basic-secondary": "#00000073",
    "--sjs2-color-fg-basic-tertiary": "#0000004D",
    "--sjs2-color-fg-neutral-primary": "#FFFFFF",
    "--sjs2-color-fg-brand-primary": "#19B394",
    "--sjs2-color-fg-accent-primary": "#19B394",
    "--sjs2-color-fg-note-primary": "#3A6FC4",
    "--sjs2-color-fg-positive-primary": "#19B394",
    "--sjs2-color-fg-warning-primary": "#E68A12",
    "--sjs2-color-fg-alert-primary": "#CC0938",
    "--sjs2-color-fg-static-main-primary": "#FFFFFF",
    "--sjs2-color-fg-static-sub-primary": "#000000E8",
    "--sjs2-color-fg-state-common-disabled": "#00000066",
    "--sjs2-color-border-basic-primary": "#000000E8",
    "--sjs2-color-border-basic-secondary": "#00000029",
    "--sjs2-color-border-brand-primary": "#19B394",
    "--sjs2-color-border-accent-primary": "#FF9814",
    "--sjs2-color-border-note-primary": "#437FD9",
    "--sjs2-color-border-positive-primary": "#19B394",
    "--sjs2-color-border-warning-primary": "#FF9814",
    "--sjs2-color-border-alert-primary": "#E50A3E",
    "--sjs2-color-border-neutral-primary": "#FFFFFF",
    "--sjs2-color-border-static-main-primary": "#FFFFFF",
    "--sjs2-color-border-static-sub-primary": "#000000E8",
    "--sjs2-color-control-formbox-default-bg": "#F5F5F5",
    "--sjs2-color-control-formbox-default-border": "#00000029",
    "--sjs2-color-control-formbox-disabled-bg": "#FFFFFF",
    "--sjs2-color-control-formbox-disabled-border": "#CDCDCD",
    "--sjs2-color-control-formbox-readonly-bg": "#FFFFFF",
    "--sjs2-color-control-formbox-readonly-border": "#CDCDCD",
    "--sjs2-color-control-formbox-focused-bg": "#F5F5F5",
    "--sjs2-color-control-formbox-focused-border": "#19B394",
    "--sjs2-color-control-formbox-invalid-bg": "#F5F5F5",
    "--sjs2-color-control-formbox-invalid-border": "#E50A3E",
    "--sjs2-color-control-formbox-highlighted-bg": "#F5F5F5",
    "--sjs2-color-control-formbox-highlighted-border": "#000000E8",
    "--sjs2-color-control-input-default-line": "#00000029",
    "--sjs2-color-control-input-default-value": "#000000E8",
    "--sjs2-color-control-input-default-placeholder": "#00000073",
    "--sjs2-color-control-input-default-label": "#00000073",
    "--sjs2-color-control-input-default-limit": "#00000073",
    "--sjs2-color-control-input-default-icon": "#0000004D",
    "--sjs2-color-control-input-disabled-line": "#CDCDCD",
    "--sjs2-color-control-input-disabled-value": "#CDCDCD",
    "--sjs2-color-control-input-disabled-placeholder": "#CDCDCD",
    "--sjs2-color-control-input-disabled-label": "#CDCDCD",
    "--sjs2-color-control-input-disabled-limit": "#CDCDCD",
    "--sjs2-color-control-input-disabled-icon": "#CDCDCD",
    "--sjs2-color-control-input-readonly-line": "#CDCDCD",
    "--sjs2-color-control-input-readonly-value": "#000000E8",
    "--sjs2-color-control-input-readonly-placeholder": "#00000073",
    "--sjs2-color-control-input-readonly-label": "#00000073",
    "--sjs2-color-control-input-readonly-limit": "#00000073",
    "--sjs2-color-control-input-readonly-icon": "#0000004D",
    "--sjs2-color-control-check-false-default-bg": "#F5F5F5",
    "--sjs2-color-control-check-false-default-border": "#00000029",
    "--sjs2-color-control-check-false-disabled-bg": "#FFFFFF",
    "--sjs2-color-control-check-false-disabled-border": "#00000029",
    "--sjs2-color-control-check-false-readonly-bg": "#FFFFFF",
    "--sjs2-color-control-check-false-readonly-border": "#00000029",
    "--sjs2-color-control-check-false-focused-bg": "#F5F5F5",
    "--sjs2-color-control-check-false-focused-border": "#19B394",
    "--sjs2-color-control-check-false-hovered-bg": "#E8E8E8",
    "--sjs2-color-control-check-false-hovered-border": "#00000029",
    "--sjs2-color-control-check-true-default-bg": "#19B394",
    "--sjs2-color-control-check-true-default-border": "#19B394",
    "--sjs2-color-control-check-true-default-icon": "#FFFFFF",
    "--sjs2-color-control-check-true-disabled-bg": "#FFFFFF",
    "--sjs2-color-control-check-true-disabled-border": "#00000029",
    "--sjs2-color-control-check-true-disabled-icon": "#B3B2B2",
    "--sjs2-color-control-check-true-readonly-bg": "#FFFFFF",
    "--sjs2-color-control-check-true-readonly-border": "#00000029",
    "--sjs2-color-control-check-true-readonly-icon": "#B3B2B2",
    "--sjs2-color-control-check-true-focused-bg": "#FFFFFF",
    "--sjs2-color-control-check-true-focused-border": "#19B394",
    "--sjs2-color-control-check-true-focused-icon": "#19B394",
    "--sjs2-color-control-check-true-hovered-bg": "#14A48B",
    "--sjs2-color-control-check-true-hovered-border": "#14A48B",
    "--sjs2-color-control-check-true-hovered-icon": "#FFFFFF",
    "--sjs2-color-control-segmented-false-default-bg": "#F3F3F300",
    "--sjs2-color-control-segmented-false-default-border": "#0000002900",
    "--sjs2-color-control-segmented-false-default-value": "#000000E8",
    "--sjs2-color-control-segmented-false-disabled-bg": "#FFFFFF",
    "--sjs2-color-control-segmented-false-disabled-border": "#0000002900",
    "--sjs2-color-control-segmented-false-disabled-value": "#CDCDCD",
    "--sjs2-color-control-segmented-false-readonly-bg": "#FFFFFF",
    "--sjs2-color-control-segmented-false-readonly-border": "#0000002900",
    "--sjs2-color-control-segmented-false-readonly-value": "#B3B2B2",
    "--sjs2-color-control-segmented-false-focused-bg": "#F3F3F3",
    "--sjs2-color-control-segmented-false-focused-border": "#19B394",
    "--sjs2-color-control-segmented-false-focused-value": "#000000E8",
    "--sjs2-color-control-segmented-false-hovered-bg": "#E8E8E8",
    "--sjs2-color-control-segmented-false-hovered-border": "#00000029",
    "--sjs2-color-control-segmented-false-hovered-value": "#000000E8",
    "--sjs2-color-control-segmented-true-default-bg": "#FFFFFF",
    "--sjs2-color-control-segmented-true-default-border": "#00000029",
    "--sjs2-color-control-segmented-true-default-value": "#19B394",
    "--sjs2-color-control-segmented-true-disabled-bg": "#F8F8F8",
    "--sjs2-color-control-segmented-true-disabled-border": "#0000002900",
    "--sjs2-color-control-segmented-true-disabled-value": "#B3B2B2",
    "--sjs2-color-control-segmented-true-readonly-bg": "#FFFFFF",
    "--sjs2-color-control-segmented-true-readonly-border": "#00000029",
    "--sjs2-color-control-segmented-true-readonly-value": "#000000E8",
    "--sjs2-color-control-segmented-true-focused-bg": "#FFFFFF",
    "--sjs2-color-control-segmented-true-focused-border": "#19B394",
    "--sjs2-color-control-segmented-true-focused-value": "#19B394",
    "--sjs2-color-control-toggle-false-default-bg": "#F5F5F5",
    "--sjs2-color-control-toggle-false-default-border": "#00000029",
    "--sjs2-color-control-toggle-false-default-icon": "#00000073",
    "--sjs2-color-control-toggle-false-disabled-bg": "#F5F5F5",
    "--sjs2-color-control-toggle-false-disabled-border": "#00000029",
    "--sjs2-color-control-toggle-false-disabled-icon": "#0000004D",
    "--sjs2-color-control-toggle-false-readonly-bg": "#F5F5F5",
    "--sjs2-color-control-toggle-false-readonly-border": "#00000029",
    "--sjs2-color-control-toggle-false-readonly-icon": "#0000004D",
    "--sjs2-color-control-toggle-false-focused-bg": "#F5F5F5",
    "--sjs2-color-control-toggle-false-focused-border": "#19B394",
    "--sjs2-color-control-toggle-false-focused-icon": "#00000073",
    "--sjs2-color-control-toggle-false-hovered-bg": "#E8E8E8",
    "--sjs2-color-control-toggle-false-hovered-border": "#00000029",
    "--sjs2-color-control-toggle-false-hovered-icon": "#00000073",
    "--sjs2-color-control-toggle-true-default-bg": "#19B394",
    "--sjs2-color-control-toggle-true-default-border": "#19B394",
    "--sjs2-color-control-toggle-true-default-icon": "#FFFFFF",
    "--sjs2-color-control-toggle-true-disabled-bg": "#F3F3F3",
    "--sjs2-color-control-toggle-true-disabled-border": "#00000029",
    "--sjs2-color-control-toggle-true-disabled-icon": "#FFFFFF",
    "--sjs2-color-control-toggle-true-readonly-bg": "#F3F3F3",
    "--sjs2-color-control-toggle-true-readonly-border": "#00000029",
    "--sjs2-color-control-toggle-true-readonly-icon": "#FFFFFF",
    "--sjs2-color-control-toggle-true-focused-bg": "#FFFFFF",
    "--sjs2-color-control-toggle-true-focused-border": "#19B394",
    "--sjs2-color-control-toggle-true-focused-icon": "#19B394",
    "--sjs2-color-control-toggle-true-hovered-bg": "#14A48B",
    "--sjs2-color-control-toggle-true-hovered-border": "#19B394",
    "--sjs2-color-control-toggle-true-hovered-icon": "#FFFFFF",
    "--sjs2-color-control-message-bg": "#E50A3E1A",
    "--sjs2-color-control-message-icon": "#CC0938",
    "--sjs2-color-control-message-text": "#000000E8",
    "--sjs2-color-data-chart-bg-color-1": "#84CAD4",
    "--sjs2-color-data-chart-bg-color-2": "#3A99FB",
    "--sjs2-color-data-chart-bg-color-3": "#FF6771",
    "--sjs2-color-data-chart-bg-color-4": "#1DB496",
    "--sjs2-color-data-chart-bg-color-5": "#FFC152",
    "--sjs2-color-data-chart-bg-color-6": "#ABA1FF",
    "--sjs2-color-data-chart-bg-color-7": "#7D8CA5",
    "--sjs2-color-data-chart-bg-color-8": "#4FC46C",
    "--sjs2-color-data-chart-bg-color-9": "#E87BCB",
    "--sjs2-color-data-chart-bg-color-10": "#4E6198",
    "--sjs2-color-data-chart-bg-color-1-tinted": "#84CAD499",
    "--sjs2-color-data-chart-bg-color-2-tinted": "#3A99FB99",
    "--sjs2-color-data-chart-bg-color-3-tinted": "#FF677199",
    "--sjs2-color-data-chart-bg-color-4-tinted": "#1DB49699",
    "--sjs2-color-data-chart-bg-color-5-tinted": "#FFC15299",
    "--sjs2-color-data-chart-bg-color-6-tinted": "#ABA1FF99",
    "--sjs2-color-data-chart-bg-color-7-tinted": "#7D8CA599",
    "--sjs2-color-data-chart-bg-color-8-tinted": "#4FC46C99",
    "--sjs2-color-data-chart-bg-color-9-tinted": "#E87BCB99",
    "--sjs2-color-data-chart-bg-color-10-tinted": "#4E619899",
    "--sjs2-color-data-chart-fg-on-color-1": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-2": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-3": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-4": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-5": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-6": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-7": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-8": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-9": "#FFFFFF",
    "--sjs2-color-data-chart-fg-on-color-10": "#FFFFFF",
    "--sjs2-color-data-chart-border-color-1": "#84CAD4",
    "--sjs2-color-data-chart-border-color-2": "#3A99FB",
    "--sjs2-color-data-chart-border-color-3": "#FF6771",
    "--sjs2-color-data-chart-border-color-4": "#1DB496",
    "--sjs2-color-data-chart-border-color-5": "#FFC152",
    "--sjs2-color-data-chart-border-color-6": "#ABA1FF",
    "--sjs2-color-data-chart-border-color-7": "#7D8CA5",
    "--sjs2-color-data-chart-border-color-8": "#4FC46C",
    "--sjs2-color-data-chart-border-color-9": "#E87BCB",
    "--sjs2-color-data-chart-border-color-10": "#4E6198",
    "--sjs2-color-data-grid-fg-label": "#000000E8",
    "--sjs2-color-data-grid-border-line": "#DCDCDC",
    "--sjs2-color-data-grid-border-axis": "#000000E8",
    "--sjs2-opacity-visible": "100%",
    "--sjs2-opacity-hovered": "100%",
    "--sjs2-opacity-pressed": "100%",
    "--sjs2-opacity-disabled": "25%",
    "--sjs2-opacity-hidden": "0%",
    "--sjs2-border-width-default": "1px",
    "--sjs2-border-width-a11y": "4px",
    "--sjs2-border-spread-form-default": "1px",
    "--sjs2-border-spread-form-hovered": "1px",
    "--sjs2-border-spread-form-pressed": "1px",
    "--sjs2-border-spread-form-focused": "2px",
    "--sjs2-border-spread-form-highlighted": "2px",
    "--sjs2-border-spread-form-disabled": "1px",
    "--sjs2-border-spread-form-invalid": "2px",
    "--sjs2-border-spread-form-readonly": "1px",
    "--sjs2-border-spread-trigger-default": "1px",
    "--sjs2-border-spread-trigger-hovered": "1px",
    "--sjs2-border-spread-trigger-pressed": "1px",
    "--sjs2-border-spread-trigger-focused": "2px",
    "--sjs2-border-spread-trigger-disabled": "1px",
    "--sjs2-border-spread-surface-default": "1px",
    "--sjs2-border-spread-surface-hovered": "1px",
    "--sjs2-border-spread-surface-pressed": "1px",
    "--sjs2-border-spread-surface-focused": "2px",
    "--sjs2-border-spread-surface-disabled": "1px",
    "--sjs2-border-spread-elevated-default": "2px",
    "--sjs2-border-spread-floating-default": "4px",
    "--sjs2-border-blur-form-default": "0",
    "--sjs2-border-blur-form-hovered": "0",
    "--sjs2-border-blur-form-pressed": "0",
    "--sjs2-border-blur-form-focused": "0",
    "--sjs2-border-blur-form-highlighted": "0",
    "--sjs2-border-blur-form-disabled": "0",
    "--sjs2-border-blur-form-invalid": "0",
    "--sjs2-border-blur-form-readonly": "0",
    "--sjs2-border-blur-trigger-default": "0",
    "--sjs2-border-blur-trigger-hovered": "0",
    "--sjs2-border-blur-trigger-pressed": "0",
    "--sjs2-border-blur-trigger-focused": "0",
    "--sjs2-border-blur-trigger-disabled": "0",
    "--sjs2-border-blur-surface-default": "4",
    "--sjs2-border-blur-surface-hovered": "4",
    "--sjs2-border-blur-surface-pressed": "4",
    "--sjs2-border-blur-surface-focused": "0",
    "--sjs2-border-blur-surface-disabled": "0",
    "--sjs2-border-blur-elevated-default": "8px",
    "--sjs2-border-blur-floating-default": "12px",
    "--sjs2-border-offset-x-form-default": "0",
    "--sjs2-border-offset-x-form-hovered": "0",
    "--sjs2-border-offset-x-form-pressed": "0",
    "--sjs2-border-offset-x-form-focused": "0",
    "--sjs2-border-offset-x-form-highlighted": "0",
    "--sjs2-border-offset-x-form-disabled": "0",
    "--sjs2-border-offset-x-form-invalid": "0",
    "--sjs2-border-offset-x-form-readonly": "0",
    "--sjs2-border-offset-x-trigger-default": "0",
    "--sjs2-border-offset-x-trigger-hovered": "0",
    "--sjs2-border-offset-x-trigger-pressed": "0",
    "--sjs2-border-offset-x-trigger-focused": "0",
    "--sjs2-border-offset-x-trigger-disabled": "0",
    "--sjs2-border-offset-x-surface-default": "0",
    "--sjs2-border-offset-x-surface-hovered": "0",
    "--sjs2-border-offset-x-surface-pressed": "0",
    "--sjs2-border-offset-x-surface-focused": "0",
    "--sjs2-border-offset-x-surface-disabled": "0",
    "--sjs2-border-offset-x-elevated-default": "0",
    "--sjs2-border-offset-x-floating-default": "0",
    "--sjs2-border-offset-y-form-default": "0",
    "--sjs2-border-offset-y-form-hovered": "0",
    "--sjs2-border-offset-y-form-pressed": "0",
    "--sjs2-border-offset-y-form-focused": "0",
    "--sjs2-border-offset-y-form-highlighted": "0",
    "--sjs2-border-offset-y-form-disabled": "0",
    "--sjs2-border-offset-y-form-invalid": "0",
    "--sjs2-border-offset-y-form-readonly": "0",
    "--sjs2-border-offset-y-trigger-default": "0",
    "--sjs2-border-offset-y-trigger-hovered": "0",
    "--sjs2-border-offset-y-trigger-pressed": "0",
    "--sjs2-border-offset-y-trigger-focused": "0",
    "--sjs2-border-offset-y-trigger-disabled": "0",
    "--sjs2-border-offset-y-surface-default": "2px",
    "--sjs2-border-offset-y-surface-hovered": "2px",
    "--sjs2-border-offset-y-surface-pressed": "2px",
    "--sjs2-border-offset-y-surface-focused": "0px",
    "--sjs2-border-offset-y-surface-disabled": "0px",
    "--sjs2-border-offset-y-elevated-default": "4px",
    "--sjs2-border-offset-y-floating-default": "6px"
  }
} as const;

export default sc2020Theme;
